name: Monthly Snapshot and Deploy

on:
    workflow_dispatch:
        inputs:
            skip-deploy:
                description: 'Skip build and deploy steps (true/false)'
                required: false
                default: 'false'
            restrict-last-day:
                description: 'Restrict snapshot to last day of month (true/false)'
                required: false
                default: 'true'
            dry-run:
                description: 'Run snapshot without committing or creating PR (true/false)'
                required: false
                default: 'false'
    schedule:
        - cron: '0 21 28-31 * *'

permissions:
    contents: write
    pull-requests: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  ref: master

            - name: Check if Today is the Last Day of the Month in EET
              id: check_last_day
              shell: bash
              run: |
                  CURRENT_DATE=$(TZ="Europe/Sofia" date '+%Y-%m-%d')
                  TOMORROW_DATE=$(TZ="Europe/Sofia" date -d "$CURRENT_DATE + 1 day" '+%Y-%m-%d')
                  CURRENT_MONTH=$(TZ="Europe/Sofia" date '+%m')
                  TOMORROW_MONTH=$(TZ="Europe/Sofia" date -d "$TOMORROW_DATE" '+%m')
                  if [ "$CURRENT_MONTH" != "$TOMORROW_MONTH" ]; then
                      echo "It's the last day of the month in EET."
                      echo "is_last_day=true" >> $GITHUB_OUTPUT
                  else
                      echo "Not the last day of the month in EET."
                      echo "is_last_day=false" >> $GITHUB_OUTPUT
                  fi

            - name: Stop if Not Last Day and Restricted
              if: ${{ (github.event_name == 'schedule' || inputs.restrict-last-day == 'true') && steps.check_last_day.outputs.is_last_day != 'true' }}
              run: |
                  echo "Stopping workflow: Not the last day of the month ($(TZ=\"Europe/Sofia\" date '+%Y-%m-%d'))."
                  exit 0

            - name: Warn if Not Last Day for Workflow Dispatch
              if: ${{ github.event_name == 'workflow_dispatch' && steps.check_last_day.outputs.is_last_day != 'true' && inputs.restrict-last-day != 'true' }}
              run: |
                  echo "WARNING: Running snapshot on a non-last day of the month ($(TZ=\"Europe/Sofia\" date '+%Y-%m-%d')). Ensure this is intentional."

            - name: Setup Node.js Environment
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Snapshot Script
              env:
                  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  CLICKUP_SPACE_ID: ${{ secrets.CLICKUP_SPACE_ID }}
              run: yarn snapshot

            - name: Create and Push Snapshot Branch
              id: commit_snapshot
              if: ${{ inputs.dry-run != 'true' }}
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "actions@github.com"
                  BRANCH_NAME="snapshot-$(date '+%Y-%m')"
                  echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
                  git checkout -b "$BRANCH_NAME"
                  git add src/data/snapshots/*.json
                  if git diff --staged --quiet; then
                      echo "No changes to commit"
                      echo "has_changes=false" >> $GITHUB_OUTPUT
                  else
                      git commit -m "Add snapshot for $(date '+%Y-%m')"
                      git push origin "$BRANCH_NAME"
                      echo "has_changes=true" >> $GITHUB_OUTPUT
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Pull Request
              if: ${{ inputs.dry-run != 'true' && steps.commit_snapshot.outputs.has_changes == 'true' }}
              run: |
                  gh pr create --title "Add snapshot for $(date '+%Y-%m')" --body "Automated snapshot for $(date '+%Y-%m')" --base master --head "${{ steps.commit_snapshot.outputs.branch_name }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build the Website
              if: ${{ inputs.dry-run != 'true' && inputs.skip-deploy != 'true' }}
              run: yarn build

            - name: Install Surge CLI
              if: ${{ inputs.dry-run != 'true' && inputs.skip-deploy != 'true' }}
              run: npm install -g surge

            - name: Deploy to Surge Production
              if: ${{ inputs.dry-run != 'true' && inputs.skip-deploy != 'true' }}
              env:
                  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
              run: |
                  echo "Deploying to production domain vitosha-tulip.surge.sh"
                  surge --project ./build --domain vitosha-tulip.surge.sh --token "$SURGE_TOKEN"

            - name: Verify Deployment
              if: ${{ inputs.dry-run != 'true' && inputs.skip-deploy != 'true' }}
              run: |
                  echo "Verifying that vitosha-tulip.surge.sh is live..."
                  curl -s -o /dev/null -w "%{http_code}" https://vitosha-tulip.surge.sh | grep 200
